
model: 
  pretrained_model_name: google/vit-base-patch16-224-in21k
  num_classes: 10
  dropout: 0
  hidden_layers: 3
  hidden_dim: 512
  batch_norm: true
  layer_norm: false
  hidden_activation: GELU
  output_activation: null
dataset: blanchon/EuroSAT_RGB
training:
  freeze_backbone: true
  batch_size: 32
  num_workers: 8
  num_epochs: 2
  learning_rate: 0.00001
  weight_decay: 0.0001
  warmup_steps: 1000
  lr_scheduler: linear
  lr_scheduler_params:
    num_warmup_steps: 1000
    num_training_steps: 10000
    warmup_ratio: 0.1
    final_lr: 0.00001
    power: 2.0
    cycle: false
    last_epoch: -1
    verbose: false
  save_dir: ./checkpoints


  
